// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfurwthocpxsvzgnsbgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdXJ3dGhvY3B4c3Z6Z25zYmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTgwODQsImV4cCI6MjA1OTY3NDA4NH0.OPw5VDtMS90J5XyrU551cQoFNhJ0q65O2jaBVJVb_SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);